/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorderedes.gui;

import com.sun.glass.ui.Application;
import gerenciadorderedes.util.Perfis;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ricardo
 */
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalGUI
     */
    public PrincipalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jPrincipal = new javax.swing.JDesktopPane();
        jInternalPerfis = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPerfis = new javax.swing.JList<>();
        jInternalAdaptadores = new javax.swing.JInternalFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAdaptadores = new javax.swing.JTextArea();
        jInternalDHCP = new javax.swing.JInternalFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        textDHCP = new javax.swing.JTextArea();
        geral = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        textPrincipal = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButtonNetworks2 = new javax.swing.JButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButtonPreferencias2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalPerfis.setBackground(new java.awt.Color(51, 51, 51));
        jInternalPerfis.setClosable(true);
        jInternalPerfis.setIconifiable(true);
        jInternalPerfis.setMaximizable(true);
        jInternalPerfis.setResizable(true);
        jInternalPerfis.setTitle("Perfis");
        jInternalPerfis.setVisible(true);

        listPerfis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listPerfis);

        javax.swing.GroupLayout jInternalPerfisLayout = new javax.swing.GroupLayout(jInternalPerfis.getContentPane());
        jInternalPerfis.getContentPane().setLayout(jInternalPerfisLayout);
        jInternalPerfisLayout.setHorizontalGroup(
            jInternalPerfisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jInternalPerfisLayout.setVerticalGroup(
            jInternalPerfisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );

        jInternalAdaptadores.setBackground(new java.awt.Color(51, 51, 51));
        jInternalAdaptadores.setClosable(true);
        jInternalAdaptadores.setIconifiable(true);
        jInternalAdaptadores.setMaximizable(true);
        jInternalAdaptadores.setResizable(true);
        jInternalAdaptadores.setTitle("Adaptadores");
        jInternalAdaptadores.setVisible(true);

        textAdaptadores.setColumns(20);
        textAdaptadores.setRows(5);
        jScrollPane5.setViewportView(textAdaptadores);

        javax.swing.GroupLayout jInternalAdaptadoresLayout = new javax.swing.GroupLayout(jInternalAdaptadores.getContentPane());
        jInternalAdaptadores.getContentPane().setLayout(jInternalAdaptadoresLayout);
        jInternalAdaptadoresLayout.setHorizontalGroup(
            jInternalAdaptadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(jInternalAdaptadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
        );
        jInternalAdaptadoresLayout.setVerticalGroup(
            jInternalAdaptadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
            .addGroup(jInternalAdaptadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );

        jInternalDHCP.setClosable(true);
        jInternalDHCP.setIconifiable(true);
        jInternalDHCP.setMaximizable(true);
        jInternalDHCP.setResizable(true);
        jInternalDHCP.setTitle("DHCP");
        jInternalDHCP.setVisible(true);

        textDHCP.setColumns(20);
        textDHCP.setRows(5);
        jScrollPane6.setViewportView(textDHCP);

        javax.swing.GroupLayout jInternalDHCPLayout = new javax.swing.GroupLayout(jInternalDHCP.getContentPane());
        jInternalDHCP.getContentPane().setLayout(jInternalDHCPLayout);
        jInternalDHCPLayout.setHorizontalGroup(
            jInternalDHCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );
        jInternalDHCPLayout.setVerticalGroup(
            jInternalDHCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );

        geral.setBackground(new java.awt.Color(51, 51, 51));
        geral.setClosable(true);
        geral.setIconifiable(true);
        geral.setMaximizable(true);
        geral.setResizable(true);
        geral.setTitle("Geral");
        geral.setVisible(true);

        textPrincipal.setColumns(20);
        textPrincipal.setRows(5);
        jScrollPane3.setViewportView(textPrincipal);

        javax.swing.GroupLayout geralLayout = new javax.swing.GroupLayout(geral.getContentPane());
        geral.getContentPane().setLayout(geralLayout);
        geralLayout.setHorizontalGroup(
            geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        geralLayout.setVerticalGroup(
            geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        jPrincipal.setLayer(jInternalPerfis, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPrincipal.setLayer(jInternalAdaptadores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPrincipal.setLayer(jInternalDHCP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPrincipal.setLayer(geral, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPrincipalLayout = new javax.swing.GroupLayout(jPrincipal);
        jPrincipal.setLayout(jPrincipalLayout);
        jPrincipalLayout.setHorizontalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalAdaptadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInternalPerfis)
                    .addComponent(jInternalDHCP))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPrincipalLayout.setVerticalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addGroup(jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jInternalPerfis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jInternalDHCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPrincipalLayout.createSequentialGroup()
                        .addComponent(geral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalAdaptadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jInternalPerfis.getAccessibleContext().setAccessibleParent(geral);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNetworks2.setText("Escanear");
        jButtonNetworks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNetworksActionPerformed(evt);
            }
        });

        jToggleButton4.setText("Escanear Rede");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButtonPreferencias2.setText("Preferências");
        jButtonPreferencias2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreferenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNetworks2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPreferencias2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNetworks2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPreferencias2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Escanear Redes");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Exibir");

        jMenuItem11.setText("Geral");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Perfis");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Adaptadores");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem14.setText("DHCP");
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Perfis");

        jMenuItem8.setText("Novo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem4.setText("Excluir");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Editar");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Redes");

        jMenuItem6.setText("DHCP");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem9.setText("Escanear");
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Adaptadores");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPrincipal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPrincipal)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jPrincipal.add(geral);
        geral.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        jPrincipal.add(jInternalPerfis);
        jInternalPerfis.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        jPrincipal.add(jInternalAdaptadores);
        jInternalAdaptadores.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jButtonPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreferenciasActionPerformed
        //jLabel2.setText("Preferências");
        Perfil pref = new Perfil();
        pref.setVisible(true);
    }//GEN-LAST:event_jButtonPreferenciasActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButtonNetworksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNetworksActionPerformed

        Application.run(() -> {
            //status.setText("Executando...");
            //jProgressBar.setMaximum(100);
            DefaultListModel lista = new DefaultListModel();

            Process exec;
            boolean ok = false;
            ArrayList<Perfis> perfis = new ArrayList<>();
            try {
                exec = Runtime.getRuntime().exec("netsh wlan show all");
                //jProgressBar.setValue(40);
                BufferedReader input = new BufferedReader(new InputStreamReader(exec.getInputStream()));
                String lineOut;
                String temp = "";
                while ((lineOut = input.readLine()) != null) {
                    temp += lineOut + "\n";
                    if (ok) {
                        if (lineOut.contains("Todos os Perfis de Usu�rios:")) {
                            Perfis perfil = new Perfis();
                            String str = lineOut.replace("Todos os Perfis de Usu�rios:", "");
                            System.out.println(str);
                            perfil.setNome(str);
                            perfis.add(perfil);
                        }
                    }
                    if (lineOut.contains("MOSTRAR PERFIS")) {
                        ok = true;
                    } else if (ok && lineOut.contains(" MOSTRAR NOME DE PERFIS=*")) {
                        ok = false;
                    }

                }
                input.close();

                for (int i = 0; i < perfis.size(); i++) {
                    lista.addElement(perfis.get(i).getNome());
                }
                textPrincipal.setText(temp);
                listPerfis.setModel(lista);

                if (exec.waitFor() == 0) {
                    System.out.println("Executado.");
                } else {
                    System.out.println("ERRO");
                }

                //ler adaptadores
                exec = Runtime.getRuntime().exec("ipconfig /all");

                input = new BufferedReader(new InputStreamReader(exec.getInputStream()));

                temp = "";
                while ((lineOut = input.readLine()) != null) {
                    temp += lineOut + "\n";
                }
                textAdaptadores.setText(temp);
                input.close();

                //ler DHCP
                exec = Runtime.getRuntime().exec("ipconfig /release");

                input = new BufferedReader(new InputStreamReader(exec.getInputStream()));

                temp = "";
                while ((lineOut = input.readLine()) != null) {
                    temp += lineOut + "\n";
                }
                textDHCP.setText(temp);
                input.close();

                //jProgressBar.setValue(100);
            } catch (IOException | InterruptedException e) {
            }
            //status.setText("Finalizado");
        });
    }//GEN-LAST:event_jButtonNetworksActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
        
        Perfil novoPerfil = new Perfil();
        novoPerfil.show();
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame geral;
    private javax.swing.JButton jButtonNetworks;
    private javax.swing.JButton jButtonNetworks1;
    private javax.swing.JButton jButtonNetworks2;
    private javax.swing.JButton jButtonPreferencias;
    private javax.swing.JButton jButtonPreferencias1;
    private javax.swing.JButton jButtonPreferencias2;
    private javax.swing.JInternalFrame jInternalAdaptadores;
    private javax.swing.JInternalFrame jInternalDHCP;
    private javax.swing.JInternalFrame jInternalPerfis;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JDesktopPane jPrincipal;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JList<String> listPerfis;
    private javax.swing.JTextArea textAdaptadores;
    private javax.swing.JTextArea textDHCP;
    private javax.swing.JTextArea textPrincipal;
    // End of variables declaration//GEN-END:variables
}
