/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciadorderedes.gui;

import gerenciadorderedes.util.Perfis;
import com.sun.glass.ui.Application;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Label;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.snmp4j.*;
import jpcap.JpcapCaptor;
import jpcap.NetworkInterfaceAddress;
import java.io.*;
import java.net.*;
import java.util.*;
import static java.lang.System.out;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author Ricardo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPerfis = new javax.swing.JList<>();
        jButtonNetworks = new javax.swing.JButton();
        jButtonPreferencias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jProgressBar = new javax.swing.JProgressBar();
        status = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textPrincipal = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPerfis1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRedes = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAdaptadores = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        textDHCP = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        listPerfis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listPerfis);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonNetworks.setText("Escanear");
        jButtonNetworks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNetworksActionPerformed(evt);
            }
        });

        jButtonPreferencias.setText("Preferências*");
        jButtonPreferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreferenciasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciador de Redes Wi-fi");

        jToggleButton1.setText("Escanear Rede");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        textPrincipal.setColumns(20);
        textPrincipal.setRows(5);
        jScrollPane3.setViewportView(textPrincipal);

        jTabbedPane2.addTab("Geral", jScrollPane3);

        listPerfis1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listPerfis1);

        jTabbedPane2.addTab("Perfis", jScrollPane4);

        jScrollPane1.setViewportView(listRedes);

        jTabbedPane2.addTab("Redes", jScrollPane1);

        textAdaptadores.setColumns(20);
        textAdaptadores.setRows(5);
        jScrollPane5.setViewportView(textAdaptadores);

        jTabbedPane2.addTab("Adaptadores", jScrollPane5);

        textDHCP.setColumns(20);
        textDHCP.setRows(5);
        jScrollPane6.setViewportView(textDHCP);

        jTabbedPane2.addTab("DHCP", jScrollPane6);

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Salvar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(status)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(jButtonNetworks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonPreferencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTabbedPane2)))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNetworks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPreferencias))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String hex2String(byte[] input) {
        String output = "";
        for (int i = 0; i < input.length - 1; i++) {
            output += Integer.toHexString(input[i] & 0xff) + ":";
        }
        output += Integer.toHexString(input[input.length - 1] & 0xff);
        return output;
    }


    private void jButtonNetworksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNetworksActionPerformed

        Application.run(() -> {
            status.setText("Executando...");
            jProgressBar.setMaximum(100);
            DefaultListModel lista = new DefaultListModel(); 
   
            Process exec;
            boolean ok = false;
            ArrayList<Perfis> perfis = new ArrayList<>();
            try {
                exec = Runtime.getRuntime().exec("netsh wlan show all");
                jProgressBar.setValue(40);
                BufferedReader input = new BufferedReader(new InputStreamReader(exec.getInputStream()));
                String lineOut;
                String temp  = "";
                while ((lineOut = input.readLine()) != null) {
                    temp += lineOut + "\n";
                    if(ok){
                        if(lineOut.contains("Todos os Perfis de Usu�rios:")){
                            Perfis perfil = new Perfis();
                            String str = lineOut.replace("Todos os Perfis de Usu�rios:", "");
                            System.out.println(str);
                            perfil.setNome(str);
                            perfis.add(perfil);
                        }
                    }
                    if(lineOut.contains("MOSTRAR PERFIS")){
                         ok = true;                             
                    }else if(ok && lineOut.contains(" MOSTRAR NOME DE PERFIS=*")){
                        ok = false;
                    }
                   
                }
                input.close();
                
                for (int i = 0; i < perfis.size(); i++) {
                     lista.addElement(perfis.get(i).getNome());
                }
                textPrincipal.setText(temp);
                listPerfis1.setModel(lista);
                
                if (exec.waitFor() == 0) {
                    System.out.println("Executado.");
                } else {
                    System.out.println("ERRO");
                }

                //ler adaptadores
                exec = Runtime.getRuntime().exec("ipconfig /all");
                
                input = new BufferedReader(new InputStreamReader(exec.getInputStream()));

                temp = "";
                while ((lineOut = input.readLine()) != null) {
                    temp += lineOut + "\n";
                }
                textAdaptadores.setText(temp);
                input.close();
                
                //ler DHCP
                exec = Runtime.getRuntime().exec("ipconfig /release");
                
                input = new BufferedReader(new InputStreamReader(exec.getInputStream()));

                temp = "";
                while ((lineOut = input.readLine()) != null) {
                    temp += lineOut + "\n";
                }
                textDHCP.setText(temp);
                input.close();
                
                jProgressBar.setValue(100);
            } catch (IOException | InterruptedException e) {
            }
            status.setText("Finalizado");
        });
    }//GEN-LAST:event_jButtonNetworksActionPerformed

    private void jButtonPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreferenciasActionPerformed
        //jLabel2.setText("Preferências");
    }//GEN-LAST:event_jButtonPreferenciasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        //Application.run(() -> {
            status.setText("Executando...");
            jProgressBar.setMinimum(0);
            jProgressBar.setValue(1);
            jProgressBar.setMaximum(255);
            InetAddress localhost;
            try {
                localhost = InetAddress.getLocalHost();

                byte[] ip = localhost.getAddress();

                for (int i = 1; i <= 254; i++) {
                    jProgressBar.setValue(i);
                    ip[3] = (byte) i;
                    InetAddress address = InetAddress.getByAddress(ip);
                    if (address.isReachable(1000)) {
                        textPrincipal.setText(textPrincipal.getText() + address + " maquina esta ligada e pode ser pingada\n");
                        //System.out.println(address + " maquina esta ligada e pode ser pingada");
                    } else if (!address.getHostAddress().equals(address.getHostName())) {
                        textPrincipal.setText(textPrincipal.getText() + address + " maquina reconhecida por um DNSLookup\n");
                        //System.out.println(address + " maquina reconhecida por um DNSLookup");
                    } else {
                        textPrincipal.setText(textPrincipal.getText() + address + " o endereço de host e o nome do host são iguais, o host name não pode ser resolvido.\n");
                    }
                }
            } catch (UnknownHostException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            status.setText("Finalizado");
        //});
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            try {
                // What to do with the file, e.g. display it in a TextArea
                BufferedWriter saida = new BufferedWriter(new FileWriter(file));
                saida.write(textPrincipal.getText());
                saida.close();
            } catch (IOException ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNetworks;
    private javax.swing.JButton jButtonPreferencias;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList<String> listPerfis;
    private javax.swing.JList<String> listPerfis1;
    private javax.swing.JList<String> listRedes;
    private javax.swing.JLabel status;
    private javax.swing.JTextArea textAdaptadores;
    private javax.swing.JTextArea textDHCP;
    private javax.swing.JTextArea textPrincipal;
    // End of variables declaration//GEN-END:variables
}
